# Generated by Django 5.2.16 on 2026-07-09 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_profiles(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(app_label, model_name)
    UserProfile = apps.get_model("labeler", "UserProfile")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user_id=user.pk, defaults={"role": "user"})


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('tiebreaker', 'Tiebreaker')], default='user', max_length=16),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='accession_no',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='imageasset',
            name='sop_instance_uid',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.CreateModel(
            name='DraftUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('unmatched_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draft_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('tiebreaker', 'Tiebreaker')], default='user', max_length=16)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_default_profiles, migrations.RunPython.noop),
        migrations.CreateModel(
            name='DraftAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_no', models.CharField(blank=True, max_length=128)),
                ('sop_instance_uid', models.CharField(blank=True, max_length=128)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dismissed_drafts', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_annotations', to='labeler.imageasset')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='labeler.draftupload')),
            ],
            options={
                'ordering': ('image__sequence_index', 'id'),
                'indexes': [models.Index(fields=['upload', 'image'], name='labeler_dra_upload__b442e8_idx'), models.Index(fields=['accession_no', 'sop_instance_uid'], name='labeler_dra_accessi_bfcf14_idx')],
                'constraints': [models.UniqueConstraint(fields=('upload', 'image'), name='unique_draft_per_upload_image')],
            },
        ),
    ]


