# Generated by Django 5.2.16 on 2026-07-09 05:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labeler', '0002_annotation_role_imageasset_accession_no_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='draftannotation',
            name='labeler_dra_accessi_bfcf14_idx',
        ),
        migrations.AddIndex(
            model_name='draftannotation',
            index=models.Index(fields=['sop_instance_uid'], name='labeler_dra_sop_ins_8bbd87_idx'),
        ),
        migrations.AddConstraint(
            model_name='imageasset',
            constraint=models.UniqueConstraint(condition=models.Q(('sop_instance_uid', ''), _negated=True), fields=('sop_instance_uid',), name='unique_nonblank_image_sop_instance_uid'),
        ),
    ]
